# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: app-ayesh-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
        working-directory: ./server

      - name: Zip artifact for deployment
        run: |
          cd server
          zip -r ../release.zip .
        shell: bash
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app-az
          # path: .
          path: release.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app-az
          path: .

      - name: Unzip artifact for deployment
        run: unzip release.zip -d server
        
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'app-ayesh-test'
          slot-name: 'Production'
          package: server
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3A475E5C4916438388B99A8BB6E38070 }}
